bio_records/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('records/', include('records.urls', namespace='records')),
]

records/urls.py
#urls.py
from django.urls import path
from . import views

app_name = 'records'

urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('survey_list/', views.SurveyListView.as_view(), name='survey_list'),
    path('survey_create/', views.SurveyCreateView.as_view(), name='survey_create'),
    path('survey_detail/<int:pk>/', views.SurveyDetailView.as_view(), name='survey_detail'),
    path('survey_update/<int:pk>/', views.SurveyUpdateView.as_view(), name='survey_update'),
    path('survey_delete/<int:pk>/', views.SurveyDeleteView.as_view(), name='survey_delete'),
    path('record_list/', views.RecordListView.as_view(), name='record_list'),
    path('record_create/', views.RecordCreateView.as_view(), name='record_create'),
    path('record_detail/<int:pk>/', views.RecordDetailView.as_view(), name='record_detail'),
    path('record_update/<int:pk>/', views.RecordUpdateView.as_view(), name='record_update'),
    path('record_delete/<int:pk>/', views.RecordDeleteView.as_view(), name='record_delete'),
    path('species_list/', views.SpeciesListView.as_view(), name='species_list'),
    path('species_create/', views.SpeciesCreateView.as_view(), name='species_create'),
    path('species_detail/<int:pk>/', views.SpeciesDetailView.as_view(), name='species_detail'),
    path('species_update/<int:pk>/', views.SpeciesUpdateView.as_view(), name='species_update'),
    path('species_delete/<int:pk>/', views.SpeciesDeleteView.as_view(), name='species_delete'),
    path('location_list/', views.LocationListView.as_view(), name='location_list'),
    path('location_create/', views.LocationCreateView.as_view(), name='location_create'),
    path('location_detail/<int:pk>/', views.LocationDetailView.as_view(), name='location_detail'),
    path('location_update/<int:pk>/', views.LocationUpdateView.as_view(), name='location_update'),
    path('location_delete/<int:pk>/', views.LocationDeleteView.as_view(), name='location_delete'),
]

records/models.py
#models.py
from django.db import models

class Species(models.Model):
    name = models.CharField(max_length=200, verbose_name="種")
    genus = models.CharField(max_length=100, blank=True, null=True, verbose_name="属")
    family = models.CharField(max_length=100, blank=True, null=True, verbose_name="科")
    scientific_name = models.CharField(max_length=200, blank=True, null=True, verbose_name="学名")
    note = models.TextField(blank=True, null=True, verbose_name="備考")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "種"
        verbose_name_plural = "種"

class Location(models.Model):
    name = models.CharField(max_length=200, verbose_name="場所名")
    latitude = models.FloatField(blank=True, null=True, verbose_name="緯度")
    longitude = models.FloatField(blank=True, null=True, verbose_name="経度")
    note = models.TextField(blank=True, null=True, verbose_name="備考")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "場所"
        verbose_name_plural = "場所"

class Survey(models.Model):  # 調査日をまとめるモデル
    date = models.DateField(verbose_name="調査日")
    note = models.TextField(blank=True, null=True, verbose_name="調査メモ")

    def __str__(self):
        return str(self.date)

    class Meta:
        verbose_name = "調査"
        verbose_name_plural = "調査"

class Record(models.Model):
    species = models.ForeignKey(Species, on_delete=models.CASCADE, verbose_name="種")
    location = models.ForeignKey(Location, on_delete=models.CASCADE, verbose_name="採取場所")
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, verbose_name="調査日")
    count = models.IntegerField(default=1, verbose_name="個体数")
    length = models.FloatField(blank=True, null=True, verbose_name="体長(mm)")
    weight = models.FloatField(blank=True, null=True, verbose_name="湿重量(g)")
    water_temperature = models.FloatField(blank=True, null=True, verbose_name="水温(℃)")
    flow_rate = models.FloatField(blank=True, null=True, verbose_name="流速(m/s)")
    water_depth = models.FloatField(blank=True, null=True, verbose_name="水深(m)")
    note = models.TextField(blank=True, null=True, verbose_name="備考")

    def __str__(self):
        return f"{self.species.name} - {self.location.name} - {self.survey.date}"

    class Meta:
        verbose_name = "記録"
        verbose_name_plural = "記録"

records/forms.py
#forms.py
from django import forms
from .models import Species,Location, Record, Survey
from django.utils import timezone

class SpeciesForm(forms.ModelForm):
    class Meta:
        model = Species
        fields = ('name','genus','family','scientific_name','note')

class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ('name','latitude','longitude','note')

class SurveyForm(forms.ModelForm):
    date = forms.DateField(initial=timezone.now().date())
    class Meta:
        model = Survey
        fields = ('date','note')

class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ('species','location','survey','count','length','weight','water_temperature','flow_rate','water_depth','note')

records/views.py
#views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse_lazy, reverse
from .models import Species, Location, Record, Survey
from .forms import SpeciesForm, LocationForm, RecordForm, SurveyForm
from django.db.models import Q

#Home views
class HomeView(TemplateView):
    template_name = 'records/home.html'

# Survey views
class SurveyListView(ListView):
    model = Survey
    template_name = 'records/survey_list.html'
    context_object_name = 'surveys'

    def get_queryset(self):
        queryset = super().get_queryset()
        survey_query_y = self.request.GET.get('survey_y')
        survey_query_m = self.request.GET.get('survey_m')
        survey_query_d = self.request.GET.get('survey_d')

        if survey_query_y:
            queryset = queryset.filter(date__year=survey_query_y)
        if survey_query_m:
            queryset = queryset.filter(date__month=survey_query_m)
        if survey_query_d:
            queryset = queryset.filter(date__date=survey_query_d)

        queryset = queryset.order_by('-date')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['survey_query_y'] = self.request.GET.get('survey_y', '')
        context['survey_query_m'] = self.request.GET.get('survey_m', '')
        context['survey_query_d'] = self.request.GET.get('survey_d', '')
        return context

class SurveyDetailView(DetailView):
        model = Survey
        template_name = 'records/survey_detail.html'
        context_object_name = 'survey'

        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['records'] = Record.objects.filter(survey=self.object)
            return context

class SurveyCreateView(CreateView):
    model = Survey
    form_class = SurveyForm
    template_name = 'records/survey_create.html'
    success_url = reverse_lazy('records:survey_list')
    
class SurveyUpdateView(UpdateView):
    model = Survey
    form_class = SurveyForm
    template_name = 'records/survey_update.html'
    context_object_name = 'survey'

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Survey, pk=pk)

    def get_success_url(self):
        return reverse_lazy('records:survey_detail', kwargs={'pk': self.object.pk})

class SurveyDeleteView(DeleteView):
    model = Survey
    template_name = 'records/survey_delete.html'
    context_object_name = 'survey'
    success_url = reverse_lazy('records:survey_list')

# Record views
class RecordListView(ListView):
    model = Record
    template_name = 'records/record_list.html'
    context_object_name = 'records'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        species_query = self.request.GET.get('species')
        location_query = self.request.GET.get('location')
        survey_query_y = self.request.GET.get('survey_y')
        survey_query_m = self.request.GET.get('survey_m')
        survey_query_d = self.request.GET.get('survey_d')
        survey_query_date = self.request.GET.get('survey_date')

        if species_query:
            queryset = queryset.filter(
                Q(species__name__icontains=species_query) |
                Q(species__genus=species_query) |
                Q(species__family=species_query) |
                Q(species__scientific_name__icontains=species_query)
            )
        if location_query:
            queryset = queryset.filter(location__name__icontains=location_query)
        if survey_query_y:
            queryset = queryset.filter(survey__date__year=survey_query_y)
        if survey_query_m:
            queryset = queryset.filter(survey__date__month=survey_query_m)
        if survey_query_d:
            queryset = queryset.filter(survey__date__day=survey_query_d)
        if survey_query_date:
            queryset = queryset.filter(survey__date=survey_query_date)
        
        queryset = queryset.order_by('-survey__date', 'location__name', 'species__name')
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['species_query'] = self.request.GET.get('species', '')
        context['location_query'] = self.request.GET.get('location', '')
        context['survey_query_y'] = self.request.GET.get('survey_y', '')
        context['survey_query_m'] = self.request.GET.get('survey_m', '')
        context['survey_query_d'] = self.request.GET.get('survey_d', '')
        return context

class RecordDetailView(DetailView):
    model = Record
    template_name = 'records/record_detail.html'
    context_object_name = 'record'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['species'] = self.object.species
        context['location'] = self.object.location
        context['survey'] = self.object.survey
        return context

class RecordCreateView(CreateView):
    model = Record
    form_class = RecordForm
    template_name = 'records/record_create.html'
    success_url = reverse_lazy('records:record_list')

class RecordUpdateView(UpdateView):
    model = Record
    form_class = RecordForm
    template_name = 'records/record_update.html'
    context_object_name = 'record'

    def get_success_url(self):
        return reverse_lazy('records:record_detail', kwargs={'pk': self.object.pk})

class RecordDeleteView(DeleteView):
    model = Record
    template_name = 'records/record_delete.html'
    context_object_name = 'record'
    success_url = reverse_lazy('records:record_list')

# Species views
class SpeciesListView(ListView):
    model = Species
    template_name = 'records/species_list.html'
    context_object_name = 'species'

    def get_queryset(self):
        queryset = super().get_queryset()
        name_query = self.request.GET.get('name')
        genus_query = self.request.GET.get('genus')
        family_query = self.request.GET.get('family')
        scientific_name_query = self.request.GET.get('scientific_name')

        if name_query:
            queryset = queryset.filter(name__icontains=name_query)
        if genus_query:
            queryset = queryset.filter(genus__icontains=genus_query)
        if family_query:
            queryset = queryset.filter(family__icontains=family_query)
        if scientific_name_query:
            queryset = queryset.filter(scientific_name__icontains=scientific_name_query)

        queryset = queryset.order_by('family', 'genus')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name_query'] = self.request.GET.get('name', '')
        context['genus_query'] = self.request.GET.get('genus', '')
        context['family_query'] = self.request.GET.get('family', '')
        context['scientific_name_query'] = self.request.GET.get('scientific_name', '')
        return context

class SpeciesDetailView(DetailView):
    model = Species
    template_name = 'records/species_detail.html'
    context_object_name = 'species'

    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['records'] = Record.objects.filter(species=self.object)
            return context

class SpeciesCreateView(CreateView):
    model = Species
    form_class = SpeciesForm
    template_name = 'records/species_create.html'
    success_url = reverse_lazy('records:species_list')

class SpeciesUpdateView(UpdateView):
    model = Species
    form_class = SpeciesForm
    template_name = 'records/species_update.html'
    context_object_name = 'species'

    def get_success_url(self):
        return reverse_lazy('records:species_detail', kwargs={'pk': self.object.pk})

class SpeciesDeleteView(DeleteView):
    model = Species
    template_name = 'records/species_delete.html'
    context_object_name = 'species'
    success_url = reverse_lazy('records:species_list')

# Location views
class LocationListView(ListView):
    model = Location
    template_name = 'records/location_list.html'
    context_object_name = 'locations'

    def get_queryset(self):
        queryset = super().get_queryset()
        location_query = self.request.GET.get('location')

        if location_query:
            queryset = queryset.filter(name__icontains=location_query)

        queryset = queryset.order_by('name')
        return queryset
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['location_query'] = self.request.GET.get('location','')
        return context

class LocationDetailView(DetailView):
    model = Location
    template_name = 'records/location_detail.html'
    context_object_name = 'location'

    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['records'] = Record.objects.filter(location=self.object).order_by('-survey__date')
            return context

class LocationCreateView(CreateView):
    model = Location
    form_class = LocationForm
    template_name = 'records/location_create.html'
    success_url = reverse_lazy('records:location_list')

class LocationUpdateView(UpdateView):
    model = Location
    form_class = LocationForm
    template_name = 'records/location_update.html'
    context_object_name = 'location'

    def get_success_url(self):
        return reverse_lazy('records:location_detail', kwargs={'pk': self.object.pk})

class LocationDeleteView(DeleteView):
    model = Location
    template_name = 'records/location_delete.html'
    context_object_name = 'location'
    success_url = reverse_lazy('records:location_list')

templates/records/home.html
<!-- home.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>bio_records_home</title>
    <link rel="stylesheet" href="{% static 'records/records.css' %}">
</head>
<body>
    <div class="container">
        <h1>Bio_Records</h1>
        <div>このサイトでは、採捕記録の管理・閲覧ができます</div>
        <h3>新規記録を登録する</h3>
        <a href="{% url 'records:species_create' %}">種を登録</a><br>
        <a href="{% url 'records:location_create' %}">地点を登録</a><br>
        <a href="{% url 'records:survey_create' %}">調査日を登録</a><br>
        <a href="{% url 'records:record_create' %}">採捕記録を登録</a><br><br>

        <h3>採捕記録を閲覧</h3>
        <a href="{% url 'records:species_list' %}">種情報リストへ</a><br>
        <a href="{% url 'records:location_list' %}">地点リストへ</a><br>
        <a href="{% url 'records:survey_list' %}">調査日リストへ</a><br>
        <a href="{% url 'records:record_list' %}">採捕記録リストへ</a>
    </div>
</body>
</html>

templates/records/location_create.html
<!-- location_create.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Create Location</title>
    <link rel="stylesheet" href="{% static 'records/records.css' %}">
</head>
<body>
    <div class="container">
        <h1>地点登録</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">登録</button>
        </form>
        <a href="{% url 'records:location_list' %}">地点リスト</a><br>
        <a href="{% url 'records:home' %}">ホーム画面へ</a>
    </div>
</body>
</html>

templates/records/location_detail.html
<!-- location_detail.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Detail Location</title>
    <link rel="stylesheet" href="{% static 'records/records.css' %}">
</head>
<body>
    <div class="container">
        <h2>地点ID: {{ location.name }}</h2>
        <span>緯度(N°): {{ location.latitude }}</span>  
        <span>経度(E°): {{ location.longitude }}</span>
        <p>座標コピペ用: {{ location.latitude }}, {{ location.longitude }}</p>
        <p>備考: {{ location.note }}</p>

        <a href="{% url 'records:record_list' %}?location={{ location.name|urlencode }}">この地点の採捕記録</a>

        <hr>
        <h3>採捕できた種</h3>
        {% regroup records by species as species_groups %}
        <ul>
            {% for group in species_groups %}
                <li>
                    <a href="{% url 'records:species_detail' pk=group.grouper.pk %}">{{ group.grouper.name }}</a>
                </li>
            {% endfor %}
        </ul>

        <hr>
        <h3>調査日</h3>
        {% regroup records by survey as date_groups %}
        <ul>
            {% for group in date_groups %}
                <!-- group.grouper はそれぞれの Date オブジェクト (例: 2025-05-12) -->
                <li>
                    <a href="{% url 'records:survey_detail' pk=group.grouper.pk %}">{{ group.grouper.date }}</a>
                </li>
            {% endfor %}
        </ul>

        <hr>

        <a href="{% url 'records:location_update' location.pk %}">地点情報を更新</a><br>
        <a href="{% url 'records:location_delete' location.pk %}">地点情報を削除</a><br>
        <a href="{% url 'records:location_list' %}">地点リストに戻る</a><br>
        <a href="{% url 'records:home' %}">ホーム画面へ</a>
    </div>
</body>
</html>

templates/records/location_list.html
<!-- location_list.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>List Location</title>
    <link rel="stylesheet" href="{% static 'records/records.css' %}">
</head>
<body>
    <div class="container">
        <h1>地点リスト</h1>
        
        <form method="get">
            <label for="name">地点名:</label>
            <input type="text" id="location" name="location" value="{{ location_query }}">
            <button type="submit">絞り込み</button>
            <a href="{% url 'records:location_list' %}">リセット</a>
        </form>

        <ul>
            {% for location in locations %}
                <li>
                    <a href="{% url 'records:location_detail' location.pk %}">{{ location.name }}</a>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'records:location_create' %}">地点を追加</a><br>
        <a href="{% url 'records:home' %}">ホーム画面へ</a>
    </div>
</body>
</html>

templates/records/record_delete.html
<!-- record_delete.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Delete Record</title>
    <link rel="stylesheet" href="{% static 'records/records.css' %}">
</head>
<body>
    <div class="container">
        <h1>この採捕記録を本当に削除しますか？</h1>
        <form method="post">
            {% csrf_token %}
            <button type="submit">はい、削除します</button>
            <a href="{% url 'records:location_detail' object.pk %}">いいえ、採捕情報に戻ります</a>
        </form>
        <a href="{% url 'records:home' %}">ホーム画面へ</a>
    </div>
</body>
</html>

templates/records/record_detail.html
<!-- record_detail.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Detail Record</title>
    <link rel="stylesheet" href="{% static 'records/records.css' %}">
</head>
<body>
    <div class="container">
        <h1>採捕記録</h1>
        <p>種: <a href="{% url 'records:species_detail' species.pk %}">{{ species.name }}</a></p>
        <p>調査地点: <a href="{% url 'records:location_detail' location.pk %}">{{ record.location }}</a> </p>
        <p>調査日: <a href="{% url 'records:survey_detail' survey.pk %}">{{ record.survey }}</a></p>
        <p>個体数: {{ record.count }}</p>
        <p>体長: {{ record.length }}</p>
        <p>湿重量: {{ record.weight }}</p>
        <p>水温: {{ record.water_temperature }}</p>
        <p>流速: {{ record.flow_rate }}</p>
        <p>水深: {{ record.water_depth }}</p>
        <p>備考: {{ record.note }}</p>
        <a href="{% url 'records:record_update' record.pk %}">採捕記録を更新する</a>
        <a href="{% url 'records:record_delete' record.pk %}">採捕記録を削除する</a><br>
        <a href="{% url 'records:record_list' %}">採捕記録リストへ戻る</a><br>
        <a href="{% url 'records:home' %}">ホーム画面へ</a>
    </div>
</body>
</html>

templates/records/record_list.html
<!-- templates/records/record_list.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>List Record</title>
    <link rel="stylesheet" href="{% static 'records/records.css' %}">
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>採捕記録リスト</h2>

        <!-- 絞り込み -->
        <form method="get">
            <label for="species">種:</label>
            <input type="text" id="species" name="species" value="{{ species_query }}">

            <label for="location">場所:</label>
            <input type="text" id="location" name="location" value="{{ location_query }}">

            <label>調査日:</label>
            <input size="3" type="text" id="survey_y" name="survey_y" value="{{ survey_query_y }}">年
            <input size="1" type="text" id="survey_m" name="survey_m" value="{{ survey_query_m }}">月
            <input size="1" type="text" id="survey_d" name="survey_d" value="{{ survey_query_d }}">日

            <button type="submit">絞り込み</button>
            <a href="{% url 'records:record_list' %}">リセット</a>
        </form>

        <table>
            <thead>
                <tr>
                    <th>種</th>
                    <th>調査場所</th>
                    <th>調査日</th>
                    <th>個体数</th>
                    <th>備考</th>
                    <th>詳細</th>
                </tr>
            </thead>
            <tbody>
                {% for record in records %}
                <tr>
                    <td><a href="{% url 'records:species_detail' pk=record.species.pk %}">{{ record.species.name }}</a></td>
                    <td><a href="{% url 'records:location_detail' pk=record.location.pk %}">{{ record.location.name }}</a></td>
                    <td><a href="{% url 'records:survey_detail' pk=record.survey.pk %}">{{ record.survey.date }}</a></td>
                    <td>{{ record.count }}</td>
                    <td>{{ record.note }}</td>
                    <td><a href="{% url 'records:record_detail' pk=record.pk %}">詳細</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- ページネーション -->
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1&species={{ species_query }}&location={{ location_query }}&survey_y={{ survey_query_y }}&survey_m={{ survey_query_m }}&survey_d={{ survey_query_d }}">&laquo; 最初</a>
                    <a href="?page={{ page_obj.previous_page_number }}&species={{ species_query }}&location={{ location_query }}&survey_y={{ survey_query_y }}&survey_m={{ survey_query_m }}&survey_d={{ survey_query_d }}">&laquo;</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}&species={{ species_query }}&location={{ location_query }}&survey_y={{ survey_query_y }}&survey_m={{ survey_query_m }}&survey_d={{ survey_query_d }}">&raquo;</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}&species={{ species_query }}&location={{ location_query }}&survey_y={{ survey_query_y }}&survey_m={{ survey_query_m }}&survey_d={{ survey_query_d }}">最後 &raquo;</a>
                {% endif %}
            </span>
        </div>
        <br>
        <a href="{% url 'records:record_create' %}">採捕記録を追加する</a><br>
        <a href="{% url 'records:survey_list' %}">調査日リストへ</a><br>
        <a href="{% url 'records:location_list' %}">地点リストへ</a><br>
        <a href="{% url 'records:species_list' %}">生物種リストへ</a><br>
        <a href="{% url 'records:home' %}">ホーム画面へ</a>
    </div>
</body>
</html>

templates/records/species_detail.html
<!-- species_detail.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Detail Species</title>
    <link rel="stylesheet" href="{% static 'records/records.css' %}">
</head>
<body>
    <div class="container">
        <h2>種名:{{ species.name }}</h2>
        <p>属:{{ species.genus }}</p>
        <p>科:{{ species.family }}</p>
        <p>学名:{{ species.scientific_name }}</p>
        <p>備考: {{ species.note }}</p>

        <a href="{% url 'records:record_list' %}?species={{ species.name|urlencode }}">この種の採捕記録</a>

        <hr>
        <h3>採捕できた地点</h3>
        {% regroup records by location as location_groups %}
        <ul>
            {% for group in location_groups %}
                <li>
                    <a href="{% url 'records:location_detail' pk=group.grouper.pk %}">{{ group.grouper.name }}</a>
                </li>
            {% endfor %}
        </ul>


        <a href="{% url 'records:species_update' species.pk %}">種情報を更新</a>
        <a href="{% url 'records:species_delete' species.pk %}">種情報を削除</a><br>
        <a href="{% url 'records:species_list' %}">種情報リストに戻る</a><br>
        <a href="{% url 'records:home' %}">ホーム画面へ</a>
    </div>
</body>
</html>

templates/records/species_list.html
<!-- species_list.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>List Species</title>
    <link rel="stylesheet" href="{% static 'records/records.css' %}">
</head>
<body>
    <div class="container">
        <h1>種情報リスト</h1>
        
        <form method="get">
            <label for="name">種名:</label>
            <input type="text" id="name" name="name" value="{{ name_query }}">
            <label for="genus">属:</label>
            <input type="text" id="genus" name="genus" value="{{ genus_query }}">
            <label for="family">科:</label>
            <input type="text" id="family" name="family" value="{{ family_query }}">
            <label for="scientific_name">学名:</label>
            <input type="text" id="scientific_name" name="scientific_name" value="{{ scientific_name_query }}">
            <button type="submit">絞り込み</button>
            <a href="{% url 'records:species_list' %}">リセット</a>
        </form>
        
        <ul>
            {% for species in species %}
                <li>
                    <a href="{% url 'records:species_detail' species.pk %}">{{ species.name }}</a>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'records:species_create' %}">種を追加する</a><br>
        <a href="{% url 'records:home' %}">ホーム画面へ</a>
    </div>
</body>
</html>

templates/records/survey_list.html
<!-- survey_list.html -->
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List Survey</title>
    <link rel="stylesheet" href="{% static 'records/records.css' %}">
</head>
<body>
    <div class="container">
        <h2>調査日リスト</h2>
        
        <form method="get">
            <label for="survey">調査日:</label>
            <input size="3" type="text" id="survey_y" name="survey_y" value="{{ survey_query_y }}">年
            <input size="1" type="text" id="survey_m" name="survey_m" value="{{ survey_query_m }}">月
            <input size="1" type="text" id="survey_d" name="survey_d" value="{{ survey_query_d }}">日
            <button type="submit">絞り込み</button>
            <a href="{% url 'records:survey_list' %}">リセット</a>
        </form>

        <ul>
            {% for survey in surveys %}
                <li>
                    <a href="{% url 'records:survey_detail' survey.pk %}">{{ survey.date }}</a>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'records:survey_create' %}">調査日を追加</a><br>
        <a href="{% url 'records:home' %}">ホーム画面へ</a>
    </div>
</body>
</html>